---
glob: "app/views/**/*.{html,text,js}{+*,}.erb"
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Naming/VariableNumber:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false